name: pre-merge-checks

on:
  pull_request:
    branches: [ main ]


jobs:

  inital_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check code using ruff
        uses: chartboost/ruff-action@v1

      - name: Check code format using black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "~= 22.6"


      - name: Check docstrings using interrogate
        run: |
          pip install interrogate
          if [ $(interrogate -c pyproject.toml -v . -f 100 | grep "FAILED" | wc -l) = 1 ]; then
             echo "necessary docstrings missing:"
             interrogate -vv . -f 100 
             exit 1
          fi




  standard_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.11,3.12]
        
    needs: [inital_checks]
    steps:
      - uses: actions/checkout@v3      


      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Make site
        run: |
          make build





  

